/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCustomerGroupArgs } from "./CreateCustomerGroupArgs";
import { UpdateCustomerGroupArgs } from "./UpdateCustomerGroupArgs";
import { DeleteCustomerGroupArgs } from "./DeleteCustomerGroupArgs";
import { CustomerGroupFindManyArgs } from "./CustomerGroupFindManyArgs";
import { CustomerGroupFindUniqueArgs } from "./CustomerGroupFindUniqueArgs";
import { CustomerGroup } from "./CustomerGroup";
import { CustomerGroupService } from "../customerGroup.service";

@graphql.Resolver(() => CustomerGroup)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CustomerGroupResolverBase {
  constructor(
    protected readonly service: CustomerGroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CustomerGroup",
    action: "read",
    possession: "any",
  })
  async _customerGroupsMeta(
    @graphql.Args() args: CustomerGroupFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CustomerGroup])
  @nestAccessControl.UseRoles({
    resource: "CustomerGroup",
    action: "read",
    possession: "any",
  })
  async customerGroups(
    @graphql.Args() args: CustomerGroupFindManyArgs
  ): Promise<CustomerGroup[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CustomerGroup, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CustomerGroup",
    action: "read",
    possession: "own",
  })
  async customerGroup(
    @graphql.Args() args: CustomerGroupFindUniqueArgs
  ): Promise<CustomerGroup | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CustomerGroup)
  @nestAccessControl.UseRoles({
    resource: "CustomerGroup",
    action: "create",
    possession: "any",
  })
  async createCustomerGroup(
    @graphql.Args() args: CreateCustomerGroupArgs
  ): Promise<CustomerGroup> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => CustomerGroup)
  @nestAccessControl.UseRoles({
    resource: "CustomerGroup",
    action: "update",
    possession: "any",
  })
  async updateCustomerGroup(
    @graphql.Args() args: UpdateCustomerGroupArgs
  ): Promise<CustomerGroup | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CustomerGroup)
  @nestAccessControl.UseRoles({
    resource: "CustomerGroup",
    action: "delete",
    possession: "any",
  })
  async deleteCustomerGroup(
    @graphql.Args() args: DeleteCustomerGroupArgs
  ): Promise<CustomerGroup | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
